# Generated by Django 5.2.3 on 2025-07-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="title",
            new_name="name",
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("genre", models.CharField(max_length=50)),
                ("extension", models.CharField(max_length=10)),
                ("size", models.IntegerField()),
                ("download_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="moviesapp.actor"
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="moviesapp.picture",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="moviesapp.tag"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Recode",
        ),
    ]
