# Generated by Django 5.2.3 on 2025-07-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorrentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file_path", models.FileField(upload_to="torrents/")),
            ],
            options={
                "verbose_name": "TorrentFile",
                "verbose_name_plural": "TorrentFiles",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="record",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="moviesapp.picture",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="torrent_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="moviesapp.torrentfile",
            ),
        ),
    ]
