# Generated by Django 5.2.3 on 2025-07-13 10:04

import django.db.models.deletion
import django.utils.timezone
import moviesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0002_rename_title_picture_name_record_delete_recode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "ordering": ["name"],
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
            },
        ),
        migrations.AlterModelOptions(
            name="picture",
            options={
                "ordering": ["name"],
                "verbose_name": "Picture",
                "verbose_name_plural": "Pictures",
            },
        ),
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterField(
            model_name="actor",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actor",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=moviesapp.models.upload_to_actor
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(upload_to=moviesapp.models.upload_to_picture),
        ),
        migrations.AlterField(
            model_name="record",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="record",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="moviesapp.picture",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="size",
            field=models.PositiveBigIntegerField(help_text="File size in bytes"),
        ),
    ]
