# Generated by Django 5.2.3 on 2025-07-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0002_torrentfile_alter_record_picture_record_torrent_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="picture",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="torrentfile",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
