# Generated by Django 5.2.3 on 2025-07-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0003_alter_picture_image_alter_picture_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="download_url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="record",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
