# Generated by Django 5.2.3 on 2025-07-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0004_alter_record_download_url_alter_record_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image",
            field=models.ImageField(max_length=255, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="torrentfile",
            name="file_path",
            field=models.FileField(max_length=255, upload_to="torrents/"),
        ),
    ]
