# Generated by Django 5.2.3 on 2025-07-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0005_alter_picture_image_alter_torrentfile_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="unique_name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="torrentfile",
            name="unique_name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="moviesapp.picture",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="torrent_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="moviesapp.torrentfile",
            ),
        ),
    ]
