# Generated by Django 5.2.3 on 2025-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0006_picture_unique_name_torrentfile_unique_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
