# Generated by Django 5.2.3 on 2025-07-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0007_alter_record_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unique_name",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("image_path", models.ImageField(max_length=255, upload_to="images/")),
            ],
            options={
                "verbose_name": "ScreenList",
                "verbose_name_plural": "ScreenLists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="record",
            name="screenlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="moviesapp.screelist",
            ),
        ),
    ]
