# Generated by Django 5.2.3 on 2025-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0008_screelist_record_screenlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="screenlist",
        ),
        migrations.AddField(
            model_name="record",
            name="screenlist",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="records", to="moviesapp.screelist"
            ),
        ),
    ]
