# Generated by Django 5.2.3 on 2025-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0009_remove_record_screenlist_record_screenlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
